# Step_03_CleanEncode - Kaggle version (generated by build_kaggle_steps.py; step code below is the local step unchanged)
# Paste into ONE Kaggle notebook cell and Run.
# Settings: Accelerator = None (CPU is fine), Internet = Off is fine.
# Needs as a Kaggle dataset (Add Input): data.csv (thesis_project/data/data.csv).
# Result: /kaggle/working/Step_03_CleanEncode.zip (downloads automatically) -> import on the Mac with import_kaggle_run.py.

import base64, glob, io, os, shutil, subprocess, sys, time, types
from pathlib import Path

STEP = "Step_03_CleanEncode"
NEEDS = []   # extra pip packages for this step
GPU = False       # foundation-model steps need the GPU (T4)


def _pip(*a):
    subprocess.run([sys.executable, "-m", "pip", *a], check=True)


if NEEDS:
    _pip("install", "-q", *NEEDS)
if any(n.startswith("tabfm") for n in NEEDS):
    # Kaggle's old JAX/Flax crashes tabfm's import (it expects ImportError, gets AttributeError); without flax tabfm
    # falls back to its PyTorch backend, exactly like the Mac.
    _pip("uninstall", "-y", "-q", "flax")
    for k in [k for k in sys.modules if k == "tabfm" or k.startswith(("tabfm.", "flax"))]:
        del sys.modules[k]
    sys.modules["flax"] = None

import numpy as np
import pandas as pd
import torch
from IPython.display import display  # steps call display(): a notebook builtin, imported so plain scripts work too

if GPU:
    assert torch.cuda.is_available(), "No GPU - Notebook settings > Accelerator > GPU"

try:
    from kaggle_secrets import UserSecretsClient
    os.environ["HF_TOKEN"] = UserSecretsClient().get_secret("HF_TOKEN")
except Exception:
    pass

# ---- everything the step writes goes to /kaggle/working/thesis_project/<STEP>/ (same layout as the Mac) ----
PROJECT = Path("/kaggle/working/thesis_project")
OUT = PROJECT / STEP
OUT.mkdir(parents=True, exist_ok=True)
# results of earlier steps (added as a Kaggle dataset) are copied in, so step_file()/PROJECT.glob() just work
for d in glob.glob("/kaggle/input/**/Step_*", recursive=True):
    if os.path.isdir(d) and not (PROJECT / os.path.basename(d)).exists() and os.path.basename(d) != STEP:
        shutil.copytree(d, PROJECT / os.path.basename(d))

# ---- lab.py, verbatim, as an importable module `lab` ----
LAB_SRC = r'''"""Shared helpers for the thesis steps.

The dataset is loaded into Postgres automatically when the backend starts, so steps
only ever *read* it. Every file a step writes to outputs/ is saved into
thesis_project/<Step>/ once the step finishes successfully.
"""
import json
import time
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import psycopg
from sklearn.metrics import (ConfusionMatrixDisplay, accuracy_score, classification_report,
                             f1_score, roc_auc_score)
from sklearn.model_selection import train_test_split

DSN = "postgresql://lab:lab@127.0.0.1:5432/lab"
PROJECT = Path(__file__).resolve().parent.parent.parent / "thesis_project"
OUT = Path(__file__).resolve().parent / "outputs"
SEED = 42
CLASS_NAMES = ["Low", "Moderate", "High"]
SIZES = {"500": 500, "2000": 2000, "Full": None}  # training-context sizes used in steps 5-8


def load_df(table: str) -> pd.DataFrame:
    """Read a table from the local Postgres (read-only use)."""
    with psycopg.connect(DSN) as conn:
        return pd.read_sql(f'SELECT * FROM "{table}"', conn)


def step_file(step: str, name: str) -> Path:
    """Path of a file saved by an earlier step, with a clear error if that step hasn't run."""
    p = PROJECT / step / name
    if not p.exists():
        raise FileNotFoundError(f"{name} not found - run {step} first.")
    return p


def test_rows():
    """Test rows every model is scored on: number in workspace/test_rows.txt ('all' = whole test set).
    Read fresh on each call, so editing the file needs no restart."""
    v = (OUT.parent / "test_rows.txt").read_text().strip().lower()
    return None if v in ("all", "none", "") else int(v)


def load_split():
    """Train/test split from Step 4. The test set is the same stratified subset for every model."""
    tr = pd.read_csv(step_file("Step_04_TrainTestSplit", "train.csv"))
    te = pd.read_csv(step_file("Step_04_TrainTestSplit", "test.csv"))
    X_train, y_train = tr.drop(columns="hair_fall"), tr["hair_fall"]
    X_test, y_test = te.drop(columns="hair_fall"), te["hair_fall"]
    n = test_rows()
    if n and n < len(X_test):
        X_test, y_test = context(X_test, y_test, n)
    print(f"[test set] {len(X_test):,} rows (change in backend/workspace/test_rows.txt)")
    return X_train, X_test, y_train, y_test


def context(X_train, y_train, size):
    """Stratified training subset of `size` rows (None = all). Same rows for every model."""
    if size is None or size >= len(X_train):
        return X_train, y_train
    X_ctx, _, y_ctx, _ = train_test_split(X_train, y_train, train_size=size, stratify=y_train,
                                          random_state=SEED)
    return X_ctx, y_ctx


def device() -> str:
    import torch
    if torch.cuda.is_available():
        return "cuda"
    return "mps" if torch.backends.mps.is_available() else "cpu"


def predict_proba_batched(model, X, batch=500, tag=None):
    """predict_proba in batches with progress + ETA. With `tag`, finished batches are saved to
    backend/workspace/checkpoints/<tag>.npy, so a stopped or crashed run resumes where it left off."""
    ckpt = OUT.parent / "checkpoints" / f"{tag}.npy" if tag else None
    done_parts = []
    if ckpt is not None:
        ckpt.parent.mkdir(exist_ok=True)
        if ckpt.exists():
            saved = np.load(ckpt)
            if len(saved) <= len(X):
                done_parts = [saved]
                print(f"  resuming: {len(saved):,}/{len(X):,} rows already predicted", flush=True)
    start = sum(len(p) for p in done_parts)
    t0 = time.time()
    for i in range(start, len(X), batch):
        done_parts.append(model.predict_proba(X.iloc[i:i + batch]))
        done = min(i + batch, len(X))
        rate = (time.time() - t0) / (done - start)
        print(f"  predicted {done:,}/{len(X):,} rows | elapsed {time.time() - t0:,.0f}s | "
              f"ETA {rate * (len(X) - done):,.0f}s", flush=True)
        if ckpt is not None:
            np.save(ckpt, np.vstack(done_parts))
    return np.vstack(done_parts)


def evaluate(model_name, size_label, n_context, y_true, proba, fit_seconds, predict_seconds, extra=None):
    """Metrics + confusion matrix; saves metrics.json and predictions.csv to outputs/."""
    rows = y_true.index if hasattr(y_true, "index") else np.arange(len(y_true))
    y_true = np.asarray(y_true)
    y_pred = proba.argmax(axis=1)
    m = {
        "model": model_name, "size": size_label, "context_rows": int(n_context), "test_rows": int(len(y_true)),
        "accuracy": round(accuracy_score(y_true, y_pred), 4),
        "macro_f1": round(f1_score(y_true, y_pred, average="macro"), 4),
        "weighted_f1": round(f1_score(y_true, y_pred, average="weighted"), 4),
        "roc_auc_ovr": round(roc_auc_score(y_true, proba, multi_class="ovr", average="macro"), 4),
        "fit_seconds": round(fit_seconds, 1), "predict_seconds": round(predict_seconds, 1),
        **(extra or {}),
    }
    print(json.dumps(m, indent=2))
    print(classification_report(y_true, y_pred, target_names=CLASS_NAMES, digits=4))

    fig, ax = plt.subplots(figsize=(4.5, 4))
    ConfusionMatrixDisplay.from_predictions(y_true, y_pred, display_labels=CLASS_NAMES, cmap="Blues", ax=ax,
                                            colorbar=False)
    ax.set_title(f"{model_name} ({size_label}) - confusion matrix")
    fig.tight_layout()
    fig.savefig(OUT / "confusion_matrix.png", dpi=150)
    plt.show()

    (OUT / "metrics.json").write_text(json.dumps(m, indent=2))
    pd.DataFrame({"row": rows, "y_true": y_true, "y_pred": y_pred, **{f"p_{c}": proba[:, i] for i, c in enumerate(CLASS_NAMES)}}) \
        .to_csv(OUT / "predictions.csv", index=False)
    return m


def shap_report(model_name, size_label, shap_values, X_explained, seconds, extra=None):
    """Global importance bar + beeswarm (High class); saves shap_importance.csv and shap_summary.json."""
    import shap
    sv = np.stack(shap_values, axis=-1) if isinstance(shap_values, list) else np.asarray(shap_values)
    if sv.ndim == 2:  # single-output model
        sv = sv[..., None]
    feats = list(X_explained.columns)
    imp = pd.DataFrame({"feature": feats, **{f"mean_abs_{c}": np.abs(sv[:, :, i]).mean(0) for i, c in enumerate(CLASS_NAMES)}})
    imp["mean_abs_all"] = imp[[f"mean_abs_{c}" for c in CLASS_NAMES]].mean(1)
    imp = imp.sort_values("mean_abs_all", ascending=False).reset_index(drop=True)
    imp.to_csv(OUT / "shap_importance.csv", index=False)
    print(imp.round(4).to_string(index=False))

    fig, ax = plt.subplots(figsize=(7, 6))
    top = imp.head(15)[::-1]
    ax.barh(top["feature"], top["mean_abs_all"], color="#2563eb")
    ax.set_xlabel("mean |SHAP| (averaged over classes)")
    ax.set_title(f"{model_name} ({size_label}) - global feature importance")
    fig.tight_layout(); fig.savefig(OUT / "shap_global_importance.png", dpi=150); plt.show()

    plt.figure()
    shap.summary_plot(sv[:, :, 2], X_explained, show=False, max_display=15)
    plt.title(f"{model_name} ({size_label}) - SHAP for High risk")
    plt.tight_layout(); plt.savefig(OUT / "shap_beeswarm_high.png", dpi=150); plt.show()

    summary = {"model": model_name, "size": size_label, "rows_explained": int(len(X_explained)),
               "seconds": round(seconds, 1), "top_5": imp["feature"].head(5).tolist(), **(extra or {})}
    (OUT / "shap_summary.json").write_text(json.dumps(summary, indent=2))
    print(json.dumps(summary, indent=2))
    return imp
'''
sys.modules.setdefault("psycopg", types.ModuleType("psycopg"))  # lab.py imports it; Kaggle reads data.csv instead
lab = types.ModuleType("lab")
lab.__file__ = "/kaggle/working/lab.py"
exec(compile(LAB_SRC, "lab.py", "exec"), lab.__dict__)
sys.modules["lab"] = lab
lab.PROJECT, lab.OUT = PROJECT, OUT
lab.test_rows = lambda: None                  # whole test set, like the local test_rows.txt = all
lab.device = lambda: "cuda" if torch.cuda.is_available() else "cpu"


def _load_df(table):
    hits = glob.glob("/kaggle/input/**/data.csv", recursive=True)
    assert hits, "data.csv not found under /kaggle/input - add a dataset containing data.csv"
    return pd.read_csv(hits[0])


lab.load_df = _load_df

# ---- T4 (15 GB) memory workarounds: identical results, less memory ----
def _chunk_predict(cls, chunk):  # predict in slices; halve the slice on CUDA out-of-memory
    orig = cls.predict_proba

    def predict_proba(self, X, *a, **k):
        parts, i, b = [], 0, chunk
        while i < len(X):
            try:
                parts.append(orig(self, X.iloc[i:i + b] if hasattr(X, "iloc") else X[i:i + b], *a, **k))
            except torch.cuda.OutOfMemoryError:
                torch.cuda.empty_cache()
                if b == 1:
                    raise
                b = max(1, b // 2)
                print(f"  GPU out of memory -> batch size {b}", flush=True)
                continue
            i += b
        return np.vstack(parts)

    cls.predict_proba = predict_proba


if any(n.startswith("tabpfn") for n in NEEDS):
    from tabpfn import TabPFNClassifier
    _chunk_predict(TabPFNClassifier, 500)

if any(n.startswith("tabfm") for n in NEEDS):
    from tabfm import TabFMClassifier
    from tabfm import tabfm_v1_0_0_pytorch as tabfm_v1
    _chunk_predict(TabFMClassifier, 100)
    # no flash attention on the T4 -> SDPA builds the full n x n score matrix. Splitting the queries into chunks gives
    # the exact same result (softmax is per query row) with far less memory.
    _sdpa = torch.nn.functional.scaled_dot_product_attention

    def _chunked_sdpa(q, k, v, attn_mask=None, **kw):
        n, Q = q.shape[-2], 1024
        if n <= Q:
            return _sdpa(q, k, v, attn_mask=attn_mask, **kw)
        out = []
        for s in range(0, n, Q):
            m = attn_mask[..., s:s + Q, :] if attn_mask is not None and attn_mask.shape[-2] == n else attn_mask
            out.append(_sdpa(q[..., s:s + Q, :], k, v, attn_mask=m, **kw))
        return torch.cat(out, dim=-2)

    torch.nn.functional.scaled_dot_product_attention = _chunked_sdpa
    _tabfm_load = tabfm_v1.load

    def _load(*a, **k):
        k.setdefault("device", "cuda")  # load() defaults to CPU!
        net = _tabfm_load(*a, **k)
        for mod in net.modules():
            if hasattr(mod, "col_chunk_size"):
                mod.col_chunk_size = 4  # default 16 feature-columns at once -> too much memory on a T4
        return net

    tabfm_v1.load = _load


class _Tee(io.TextIOBase):  # everything printed is also saved to output.txt
    def __init__(self, *s): self.s = s
    def write(self, t):
        for x in self.s: x.write(t)
        return len(t)
    def flush(self):
        for x in self.s: x.flush()


_LOG, _NB_STDOUT = io.StringIO(), sys.stdout
sys.stdout = _Tee(_NB_STDOUT, _LOG)
if GPU:
    print(f"GPU: {torch.cuda.get_device_name(0)}")

# ======================= step code (unchanged from backend/steps/Step_03_CleanEncode.py) =======================
# Step 3 - Validate & encode
# Validate against clinical reference ranges and encode
import matplotlib.pyplot as plt
import pandas as pd
from lab import OUT, load_df

df = load_df("hairfall_dataset")
n0 = len(df)

# 1) Sanity checks
assert set(df["gender"].unique()) <= {"Female", "Male", "Other"}, "unexpected gender label"
print("Gender:", df["gender"].value_counts().to_dict())
print("Missing values:", int(df.isna().sum().sum()),
      "| Duplicate rows:", int(df.drop(columns=["id"]).duplicated().sum()))

# 2) Clinical reference check: (normal_low, normal_high, impossible_low, impossible_high)
#    Abnormal values are KEPT (they are what predicts hair fall); only impossible values are dropped.
REF = {
    "total_protein":      (6.0, 8.3, 2.0, 12.0),  # g/dL   serum total protein
    "calcium":            (8.5, 10.5, 5.0, 14.0), # mg/dL  serum calcium
    "iron":               (60, 170, 5, 500),      # ug/dL  serum iron
    "vitamin_d":          (25, 80, 1, 150),       # ng/mL  25-OH vitamin D
    "alt_liver":          (7, 56, 1, 500),        # U/L    ALT
    "manganese":          (4, 15, 0.5, 60),       # ug/L   whole-blood manganese
    "body_water_content": (45, 65, 20, 85),       # %      total body water
}
rows = []
for c, (lo, hi, ilo, ihi) in REF.items():
    below, above = int((df[c] < lo).sum()), int((df[c] > hi).sum())
    rows.append(dict(feature=c, normal_range=f"{lo}-{hi}", below_normal=below, above_normal=above,
                     impossible=int(((df[c] < ilo) | (df[c] > ihi)).sum()),
                     pct_abnormal=round(100 * (below + above) / len(df), 1)))
    df = df[(df[c] >= ilo) & (df[c] <= ihi)]
report = pd.DataFrame(rows)
display(report)
print(f"Rows removed as physiologically impossible: {n0 - len(df)}")

fig, ax = plt.subplots(figsize=(6, 3.5))
ax.barh(report["feature"], report["pct_abnormal"], color="#2563eb")
ax.set_xlabel("% of patients outside the normal range"); ax.set_title("Biomarkers outside reference ranges")
fig.tight_layout(); fig.savefig(OUT / "range_check.png", dpi=150); plt.show()

# 3) Encode gender, drop identifiers (id, full_name are personal / non-predictive)
df["gender"] = df["gender"].map({"Female": 0, "Male": 1, "Other": 2})
clean = df.drop(columns=["id", "full_name"]).reset_index(drop=True)
assert clean.isna().sum().sum() == 0
print("Clean shape:", clean.shape, "| features:", clean.shape[1] - 1)

clean.to_csv(OUT / "hairfall_clean.csv", index=False)
report.to_csv(OUT / "range_report.csv", index=False)

# ======================= end of step code =======================
sys.stdout = _NB_STDOUT
(OUT / "output.txt").write_text(_LOG.getvalue())
shutil.make_archive(f"/kaggle/working/{STEP}", "zip", root_dir=PROJECT, base_dir=STEP)
ZIP = f"/kaggle/working/{STEP}.zip"
print(f"Done -> {ZIP}   (import on the Mac: cd backend && .venv/bin/python import_kaggle_run.py ~/Downloads/{STEP}.zip)")

# Kaggle wipes the session's files when it closes, so push the zip to your computer's Downloads folder automatically
# (embedded in the page) + a manual link as a fallback.
from IPython.display import HTML, FileLink, display
b64 = base64.b64encode(open(ZIP, "rb").read()).decode()
display(HTML(f'<a id="dl" download="{STEP}.zip" href="data:application/zip;base64,{b64}">Download {STEP}.zip</a>'
             '<script>document.getElementById("dl").click()</script>'))
display(FileLink(ZIP))
