# -*- coding: utf-8 -*-
"""Question bank for the thesis viva. Each section: (title, intro, [(question, answer, star)]).
star=True marks the questions that are almost certain to be asked."""

KEY_NUMBERS = [
    ("Dataset", "21,606 records, 20 predictors, 3 tiers: Low 9,723 (45%), Moderate 7,562 (35%), High 4,321 (20%)"),
    ("Split", "Stratified 80/20, seed 42: 17,284 train / 4,322 test (1,945 Low, 1,513 Moderate, 864 High)"),
    ("CatBoost tuning", "Grid depth {4,6,8} x learning rate {0.01,0.03,0.1}, 5-fold stratified CV on macro-F1; best depth 4, lr 0.1 (CV macro-F1 0.7665)"),
    ("Accuracy", "CatBoost 78.51% | TabPFN 78.57% | TabFM 77.88% (TabFM with only 500 rows)"),
    ("Macro-F1", "0.7763 | 0.7787 | 0.7715"),
    ("ROC-AUC", "0.9189 | 0.9232 | 0.9180"),
    ("McNemar p-values", "CatBoost-TabPFN 0.904 | CatBoost-TabFM 0.199 | TabPFN-TabFM 0.108 (none significant)"),
    ("95% Wilson CI", "About +/-1.2 points: CatBoost 77.26-79.70%, TabPFN 77.33-79.77%, TabFM 76.62-79.09%"),
    ("Kappa / QWK", "Kappa 0.66 / 0.66 / 0.65; quadratic weighted kappa 0.81 / 0.81 / 0.80"),
    ("Per-class F1", "Low 0.85-0.86, Moderate 0.71 (all), High 0.76-0.78"),
    ("100 rows", "CatBoost 60.53% | TabPFN 71.54% | TabFM 74.41%"),
    ("500 rows", "CatBoost 69.64% | TabPFN 77.65% | TabFM 77.88%"),
    ("2,000 rows*", "CatBoost 74.40% | TabPFN 76.20% | TabFM 77.40% (*500-record test subset)"),
    ("Top SHAP features", "iron, stress_level, total_protein, vitamin_d, alt_liver, calcium, manganese (same 7 in all models)"),
    ("Strongest correlations", "stress_level +0.33, iron -0.31, total_protein -0.30, vitamin_d -0.26, alt_liver +0.25"),
    ("TabFM runtime", "~0.11 s/record at 500 rows, ~1.8 s/record at 2,000 rows; full 17,284-row context did not finish"),
    ("SHAP setup", "TreeExplainer (CatBoost, all 4,322 records); KernelExplainer (TabPFN 30 records, TabFM 20 records, background 15, 100 samples)"),
    ("Environment", "Python, Kaggle + Google Colab, NVIDIA T4 GPU; catboost, tabpfn, tabfm 1.0.0, shap, scikit-learn, statsmodels"),
]

SECTIONS = [
("Opening and big picture",
 "Examiners almost always start here. Practise a 1-minute and a 3-minute version of your answer.",
 [
 ("Please summarise your thesis in two minutes.",
  "I compared three models for predicting hair fall risk in three tiers (Low, Moderate, High) from clinical and lifestyle data: a tuned gradient-boosted tree (CatBoost) and two new tabular foundation models (TabPFN and TabFM) that need no training. On 4,322 test records all three reached about 78% accuracy with no significant difference. With little training data the foundation models were much better. SHAP showed the same seven biomarkers drive every model. TabFM was slow at large context. The dataset is constructed, so this is a model benchmark, not a clinical tool.", True),
 ("Why did you choose this topic?",
  "Hair loss is common, affects confidence, and has many interacting causes, so it is hard to judge by eye. Its data (lab values, lifestyle flags) are tabular, and tabular foundation models are a new and untested idea. Testing them on a health problem, and explaining them, was both useful and new.", True),
 ("What is the main contribution of your work?",
  "A fair, same-data benchmark of two independent tabular foundation models against a tuned CatBoost on hair fall risk; a matched training-size experiment showing where foundation models help; SHAP applied to all three and checked against the data; and documentation of the runtime and software problems of a newly released model (TabFM).", True),
 ("What is new in your thesis compared with earlier hair loss studies?",
  "Earlier studies used classical models (Random Forest, SVM, ensembles, neural networks), often without explanations. None tested tabular foundation models, none compared two of them with a tuned boosting model, and none varied the training size.", True),
 ("In one sentence, what is your answer to your research problem?",
  "On this dataset, zero-shot foundation models matched a tuned CatBoost without any tuning, needed far less data, and could be explained with SHAP.", False),
 ("What surprised you most?",
  "How little data the foundation models needed: with only 100 rows TabFM reached 74% while CatBoost reached 61%. And that TabFM's runtime rose so steeply with context size.", False),
 ("What would you do differently if you started again?",
  "Use a separate validation split for CatBoost early stopping, fix seeds for the SHAP samples, run the scaling experiment on the full test set with several seeds, and try to obtain a real clinical dataset.", True),
 ]),

("Problem, motivation and Nepal context",
 "Expect at least one question linking your work to Nepal. Be honest: your data are not from a Nepali clinic.",
 [
 ("What exactly is the problem you are solving?",
  "Assessing hair fall risk objectively. Risk depends on many factors together, current practice relies on self-report and late clinical checks, the literature disagrees on the best model, foundation models were untested, and accurate models are opaque.", True),
 ("How is this study relevant to Nepal?",
  "Specialist dermatology care is concentrated in cities, while basic blood tests (iron, protein, vitamin D, liver enzymes) are available in many local labs. A model that turns routine lab values and a short questionnaire into an explained risk tier could support early screening outside big hospitals. The foundation-model result also matters for Nepal because labelled health data here are usually small, and those models work well with few records.", True),
 ("Is your data from Nepal? The names in the dataset are in Nepali.",
  "The records carry Nepali names, but I removed the names before modelling and the dataset was assembled from two public sources (a Kaggle hair loss dataset and a Mendeley hair fall survey dataset) and adjusted with domain-informed relationships. So I do not claim it represents the Nepali population. Validation on real Nepali clinical data is my first recommendation.", True),
 ("Could this be used in hospitals in Nepal today?",
  "Not yet. It needs validation on real, ethically approved Nepali patient data and review by dermatologists. It is designed as decision support, not diagnosis.", True),
 ("What would it take to deploy this in a rural health post in Nepal?",
  "CatBoost is the practical choice there: it is small, fast and runs offline on a normal laptop or phone. TabPFN in my app uses a cloud API (needs internet and a token) and TabFM needs a GPU or is slow on CPU, which is harder where internet and power are unreliable. A Nepali-language form and an offline mode would also be needed.", True),
 ("Which risk factors in your data are especially relevant for Nepal?",
  "Nutrition-related markers (iron, protein, vitamin D) and anaemia, stress and sleep habits, and water quality (the hard or treated water flag). These are factors that local health workers can act on through diet and lifestyle advice. I would not state prevalence figures without a Nepali source.", False),
 ("Are there data privacy concerns for such a system in Nepal?",
  "Yes. Health records are sensitive; Nepal's Privacy Act, 2075 (2018) protects personal and health information. A real system would need consent, anonymisation, secure storage, and would avoid sending patient data to foreign cloud APIs without approval. In my study names and IDs were removed and only public data were used.", False),
 ("Why not use images of the scalp instead, like other studies?",
  "Images detect visible loss after it happens. My aim is to estimate risk earlier from lab and lifestyle data, which is cheaper to collect in Nepal and fits tabular models. Images are a different task (Shakeel et al. did it with SVM/KNN).", False),
 ("Who benefits from your research?",
  "Clinicians (consistent screening with reasons), people at risk (early warning tied to modifiable factors), ML practitioners (evidence on foundation models vs tuned trees) and future researchers (a reproducible benchmark and documented pitfalls).", False),
 ]),

("Research questions and objectives",
 "Know your four research questions by heart and which result answers each.",
 [
 ("What are your research questions?",
  "RQ1: Can TabPFN and TabFM match a tuned CatBoost, and are differences significant? RQ2: How does training context size affect the models? RQ3: Which features drive predictions, and do the models agree? RQ4: What are the computational costs and implementation limitations?", True),
 ("What is your general objective?",
  "To benchmark CatBoost, TabPFN and TabFM for explainable multi-tier hair fall risk stratification from structured clinical and lifestyle data.", True),
 ("Did you achieve all your objectives? Show me where.",
  "Yes. Objective 1 in Section 4.1 (performance and McNemar), Objective 2 in Section 4.2 (context scaling), Objective 3 in Section 4.3 (SHAP and data correlations), Objective 4 in Section 4.4 (runtime and software problems).", True),
 ("Why four research questions and not a hypothesis?",
  "The syllabus asks for research questions with matching objectives. The study still tests an implicit proposition: that zero-shot models can match a tuned model. That is examined with McNemar's test.", False),
 ("What is the scope of your study?",
  "Three-tier classification from structured tabular data only; three models; one dataset of 21,606 records; one held-out test set; SHAP explanations. Images, free text and other scalp conditions are outside scope.", False),
 ]),

("Literature review",
 "They check whether you know the key papers and the gap.",
 [
 ("Which previous studies are closest to yours?",
  "Widowati et al. (explainable multi-class hair loss severity), Sai et al. (ensemble beats individual classifiers), Patel et al. (Random Forest beats XGBoost, CatBoost, LightGBM), Chen et al. (neural networks, less interpretable), Anderson and Roberts (survey features, macro-F1), Shakeel et al. (image-based SVM/KNN).", True),
 ("What gap did you find in the literature?",
  "Conflicting evidence on the best model, no test of tabular foundation models on hair fall data, no comparison of two foundation models with a tuned boosting model, no common explanation method across models, and no study of performance with limited data.", True),
 ("Patel et al. found Random Forest better than CatBoost. Why did you not include Random Forest?",
  "My aim was to compare the strongest tuned tabular baseline with foundation models. Gradient boosting is generally stronger than Random Forest on tabular benchmarks (Grinsztajn et al., Shwartz-Ziv and Armon). Adding Random Forest and XGBoost is a good extension; Patel's result shows rankings depend on the dataset.", True),
 ("Why do tree models still beat deep learning on tabular data?",
  "Tabular data have uninformative features, irregular target functions and mixed feature types. Trees handle these well; standard neural networks are biased towards smooth functions and need more tuning (Grinsztajn et al., 2022).", False),
 ("How many sources did you review? Are they peer-reviewed?",
  "32 references, about 25 peer-reviewed papers and books (NeurIPS, Nature, ICLR, journals). The TabFM blog and the GitHub evaluation are not peer-reviewed; I say so in Section 2.5 and treat that evidence as provisional.", True),
 ("TabFM was released in 2026. How can you rely on a blog post?",
  "I did not rely on it for my conclusions. I used it only to describe the model, and I tested TabFM myself. An independent reproduction (devYRPauli) confirmed competitive accuracy but also found defects, which matches my own experience.", True),
 ("What is TabArena?",
  "A benchmark suite of tabular datasets used to compare tabular models. Google reported that TabFM beat heavily tuned gradient-boosted models there in a zero-shot setting.", False),
 ]),

("Dataset (be ready: this is the weakest point)",
 "Examiners will push hard here. Stay calm, be honest, and explain why the benchmark is still valid.",
 [
 ("Where does your data come from?",
  "Two public sources: the Kaggle Hair Loss Dataset (biomarkers) and the Mendeley Hair Fall Problem Survey Dataset (demographics and lifestyle flags). Because they came from different people, feature values were adjusted with relationships reported in the dermatology literature to build the final 21,606-record dataset.", True),
 ("So your dataset is synthetic?",
  "It is constructed, not a single clinical registry. I disclose this in Chapters 1, 3, 4 and 5. That is why I present the results as a benchmark of model behaviour on realistic relationships, not as clinical accuracy. The comparison between models is still fair because every model saw exactly the same data and split.", True),
 ("If you built the relationships into the data, isn't the SHAP result circular?",
  "Partly, and I say so. The SHAP finding shows the models recovered the built-in relationships, which is a check that they learned sensibly and that SHAP works for all three. It is not a new clinical discovery. I also compared SHAP with the correlations in the data (Section 4.3.1), and they agree.", True),
 ("Why not collect real data from Nepali hospitals?",
  "Real clinical data need ethical approval, patient consent and time beyond a one-semester project, and labelled hair fall risk data are not publicly available in Nepal. It is the first item in my future work.", True),
 ("What is the target variable and how was it defined?",
  "hair_fall with three ordered tiers: 0 Low, 1 Moderate, 2 High. It came with the dataset; I did not relabel it.", True),
 ("Describe your features.",
  "20 predictors: demographics (age, gender, family history), biomarkers (total protein, iron, calcium, vitamin D, manganese, ALT, body water, stress score 0-40), two hair-condition scores (keratine, texture), and binary flags (chronic illness, anaemia, stress, late sleep, sleep disturbance, hard water, chemical use).", True),
 ("Is your dataset balanced?",
  "No: 45% Low, 35% Moderate, 20% High. So I used stratified splitting and macro-averaged metrics, which weight each tier equally.", True),
 ("Were there missing values, duplicates or outliers?",
  "No missing values and no duplicates. Ranges were plausible (for example age 20-55, stress 0-40). I did not remove outliers because tree models and foundation models are robust to them and I wanted all models on identical data.", False),
 ("Why did total_keratine and hair_texture have no importance?",
  "Their correlation with the risk tier is almost zero (about 0.00) and their means are the same in every tier, so they carry no information in this dataset. All three models correctly ignored them.", True),
 ("The 'Other' gender has only 12 records. How did you handle it?",
  "It was kept as code 2. It is too small to analyse separately, and gender had almost no importance in any model.", False),
 ("How do you know the data are realistic?",
  "The ranges match normal clinical ranges, the directions match known associations (low iron, protein and vitamin D with more hair loss; stress with more hair loss), and no single feature separates the tiers (correlations 0.18-0.33), which is typical for real multi-factor conditions.", False),
 ]),

("Preprocessing and experimental design",
 "",
 [
 ("What preprocessing did you do?",
  "Removed id and full_name, mapped gender to 0/1/2, checked for missing values (none). No scaling or target encoding, so nothing was fitted on the data that could leak test information.", True),
 ("Why did you not scale or normalise features?",
  "Trees are unaffected by scaling, and TabPFN and TabFM are designed to take raw values and normalise internally. Leaving data raw also avoids leakage.", False),
 ("Why an 80/20 split and not cross-validation for the final results?",
  "Foundation-model inference, especially TabFM, is expensive, so repeating all models over many folds was not feasible. One large stratified test set of 4,322 records gives a precise estimate (Wilson CI about +/-1.2 points). CatBoost tuning did use 5-fold CV inside the training set.", True),
 ("Why seed 42?",
  "Any fixed seed makes the split and sampling reproducible; 42 is a common convention. A limitation is that I used only one seed.", False),
 ("Why is your research design experimental and quantitative?",
  "The questions ask for measurable comparisons of methods under controlled, identical conditions, which is what an experimental benchmark provides.", False),
 ("What was your study population and sample?",
  "The population is records describing hair fall risk factors; the full dataset of 21,606 records was used. The training partition was 17,284 and the test partition 4,322.", False),
 ]),

("CatBoost",
 "",
 [
 ("Why CatBoost as the baseline?",
  "It is a leading gradient-boosting library, handles categorical features with ordered target statistics, reduces target leakage and uses symmetric trees that resist overfitting. Tuned boosting is the standard any new tabular method must beat.", True),
 ("Explain how gradient boosting works.",
  "Trees are added one at a time. Each new tree is fitted to the negative gradient of the loss (the remaining error) of the current ensemble and added with a learning rate. Many small corrections build a strong model.", True),
 ("What are ordered target statistics and ordered boosting?",
  "When a categorical value is converted to a number using the target, CatBoost only uses records that come earlier in a random order, so a record's own label never leaks into its encoding. Ordered boosting applies the same idea to the gradient steps to reduce prediction shift.", False),
 ("What are oblivious (symmetric) trees?",
  "Trees where every node at the same depth uses the same split. They are fast, and act as a regulariser against overfitting.", False),
 ("How did you tune CatBoost?",
  "Grid search over depth {4, 6, 8} and learning rate {0.01, 0.03, 0.1} (9 combinations), each scored by 5-fold stratified cross-validation on macro-F1, with l2_leaf_reg 3, up to 1,000 iterations and early stopping after 50 rounds. Best: depth 4, learning rate 0.1, CV macro-F1 0.7665.", True),
 ("Your final CatBoost used the test set for early stopping. Isn't that leakage?",
  "Yes, it is a limitation, and I report it in Sections 3.8.4 and 5.2. The test set only chose the number of trees, not the hyperparameters. If anything it could have slightly favoured CatBoost, and CatBoost still did not beat TabPFN, so the main conclusion does not depend on it. The fix is a validation split from the training data.", True),
 ("Why was depth 4 best and not deeper trees?",
  "The relationships are fairly smooth and additive, so shallow trees generalise better; deeper trees overfit. With learning rate 0.1 the model converges in a reasonable number of trees.", False),
 ("Why only a small grid? Why not Bayesian optimisation?",
  "Depth and learning rate are the two parameters that most control complexity and speed; nine combinations kept the search within compute limits. Wider or Bayesian search could add a little accuracy and is a fair extension.", False),
 ]),

("TabPFN and TabFM (foundation models)",
 "Expect conceptual questions. Explain in-context learning simply.",
 [
 ("What is a tabular foundation model?",
  "A transformer pretrained once on millions of synthetic tables so that it learns the general skill of predicting from examples. For a new dataset you give it the labelled rows as context with the query rows, and it predicts in one forward pass, without training or tuning.", True),
 ("What is in-context learning?",
  "Learning from examples placed in the input instead of changing the model's weights. The training rows act like a prompt; the model's attention compares each query row with them.", True),
 ("How is TabPFN different from TabFM?",
  "TabPFN applies attention mainly across samples. TabFM (Google, 2026) alternates attention across rows and across columns, compresses each row, then an in-context transformer predicts. Both are zero-shot; TabFM is newer and much slower at large context in its 1.0.0 release.", True),
 ("What does 'prior-fitted network' mean?",
  "TabPFN is trained on data generated from a prior over many possible datasets (structural causal models). It learns to approximate the Bayesian posterior predictive distribution, so given the training set it outputs class probabilities directly.", False),
 ("Why did TabFM use only 500 rows?",
  "Its prediction time grew steeply with context size: about 0.11 s per record at 500 rows and 1.8 s at 2,000. The full 17,284-row run did not finish within cloud session limits. 500 rows was the largest size that completed on the full test set. I then compared all models at matched sizes to be fair.", True),
 ("Isn't comparing TabFM with 500 rows against CatBoost with 17,284 rows unfair?",
  "It is unequal, which is why I added the matched-context experiment (100, 500 and 2,000 rows for all models). At every matched size both foundation models beat CatBoost. The full-size comparison favours CatBoost, yet TabFM was still not significantly worse.", True),
 ("TabPFN was designed for small data (up to 10,000 samples). You used 17,284.",
  "Yes, beyond its reported range. It still matched CatBoost, and it did not exceed it, which suggests its advantage is largest with small data and disappears as data grows. That is consistent with my scaling results.", True),
 ("Why do foundation models need so little data?",
  "They bring prior knowledge from pretraining on many datasets, so they need fewer examples to form a good decision rule. Trees must learn splits from scratch and need enough records in each region. I did not test this explanation directly.", True),
 ("What are the drawbacks of foundation models?",
  "Prediction cost grows with context size, the training data must be available at prediction time, they are harder to explain (need model-agnostic SHAP), and new packages can have defects. TabPFN in my app also needs a cloud API token.", True),
 ("What is attention? Write the formula.",
  "Attention(Q,K,V) = softmax(Q K-transpose / sqrt(d_k)) V. Each element's query is compared with all keys; the softmax weights decide how much of each value is used.", False),
 ]),

("Evaluation metrics and statistics",
 "Very common. Be precise with definitions.",
 [
 ("Why macro-averaged metrics instead of accuracy alone?",
  "The classes are unequal (45/35/20). Macro-averaging computes each metric per class and averages with equal weight, so the smaller High tier counts as much as Low.", True),
 ("Define precision, recall and F1.",
  "Precision: of records predicted as a class, the share that truly are. Recall: of records truly in a class, the share found. F1: harmonic mean of precision and recall, high only when both are high.", True),
 ("What does ROC-AUC of 0.92 mean for a three-class problem?",
  "I used one-vs-rest: for each tier, the probability that a random record of that tier gets a higher score for it than a random record of the other tiers, averaged over the three tiers. 0.92 means very good ranking.", True),
 ("What is McNemar's test and why did you use it?",
  "A test for two classifiers on the same test records. It uses only disagreements: b records the first got right and the second wrong, c the reverse. Chi-square = (|b - c| - 1)^2 / (b + c). It suits models trained once on one split and has a low false-positive rate (Dietterich, 1998).", True),
 ("Your p-values were not significant. Does that mean the models are equal?",
  "No. It means no difference was detected; it is not proof of equivalence. To claim equivalence I would need an equivalence test (for example TOST) with a chosen margin.", True),
 ("What are Wilson confidence intervals?",
  "An interval for a proportion that behaves well even near 0 or 1 and for small samples. Mine are about +/-1.2 points on 4,322 records, and the three intervals overlap almost completely.", False),
 ("Why did you also report kappa and quadratic weighted kappa?",
  "The tiers are ordered. Kappa corrects accuracy for chance (0.65-0.66). Quadratic weighted kappa penalises big errors more (Low vs High counts 4x a neighbouring error); 0.80-0.81 shows almost all errors are between neighbours.", False),
 ("Why not statistical tests at reduced context sizes?",
  "I did not run them, so I make no significance claims there. The 2,000-row run used only 500 test records, where the interval is about +/-3.7 points. It is listed as future work.", True),
 ("What is 33.3% and 45% that you mention?",
  "33.3% is random guessing among three classes; 45% is always predicting the largest class (Low). All models reached about 78%, far above both baselines.", False),
 ]),

("Results",
 "Know every headline number (see the Key Numbers page).",
 [
 ("What are your main results?",
  "Accuracy CatBoost 78.51%, TabPFN 78.57%, TabFM 77.88%; macro-F1 0.776/0.779/0.772; ROC-AUC 0.919/0.923/0.918. McNemar p = 0.90, 0.20, 0.11, so no significant difference.", True),
 ("Which model is best?",
  "TabPFN had the highest accuracy, macro-F1 and ROC-AUC, but the differences are not significant. The best choice depends on the situation: TabPFN with limited data, CatBoost for cheap and fast deployment with lots of data.", True),
 ("Why is the Moderate class the hardest?",
  "It lies between Low and High, so it shares a boundary with both. F1 was 0.71 for all three models. An ordinal model might help; I list it as future work.", True),
 ("What kinds of errors do the models make?",
  "Almost all errors are to a neighbouring tier; Low and High were confused only 1-3 times out of about 930 errors. High-risk records were under-rated as Moderate in 27-31% of cases, far more often than Moderate was over-rated as High (7-9%).", True),
 ("Is 78% accuracy good enough?",
  "It is far above chance and the models rank risk well (AUC 0.92), but it is not precise enough to assign the exact tier with confidence, especially near Moderate. All three very different models stopped at about 78%, which suggests the limit is the information in the features, not the model.", True),
 ("Explain your context-scaling result.",
  "With 100 rows CatBoost reached 60.53% while TabPFN reached 71.54% and TabFM 74.41%. At 500 rows: 69.64%, 77.65%, 77.88%. The gap narrowed with more data and closed at full size. Foundation models needed at least five times less data to pass 70%.", True),
 ("At 2,000 rows TabFM beat TabPFN. Is TabFM better at medium sizes?",
  "I do not claim that. The 2,000-row run used only 500 test records (interval about +/-3.7 points), so the 1.2-point margin is not reliable.", True),
 ("Why did TabPFN get 77.65% at 500 rows but 76.20% at 2,000 rows? Shouldn't more data help?",
  "The two numbers use different test sets (4,322 vs 500 records), so they are not directly comparable. The 2,000-row column should only be compared across models.", True),
 ("How do your results compare with other studies?",
  "Accuracies cannot be compared directly because datasets and targets differ. In findings: my result agrees that tuned trees are strong at full data (Grinsztajn, Shwartz-Ziv), supports TabFM's benchmark claims only partly (no advantage at full data), and agrees with TabPFN being strongest on small data (Hollmann et al.).", True),
 ]),

("Explainability (SHAP)",
 "",
 [
 ("What is SHAP?",
  "Shapley Additive Explanations: from game theory, each feature is a player and the prediction is the payout. The prediction equals the baseline plus the sum of each feature's contribution. It is the only additive method satisfying local accuracy, missingness and consistency.", True),
 ("Which features were most important?",
  "The same seven in all three models: iron, stress level, total protein, vitamin D, ALT (liver), calcium and manganese. High stress and ALT raise High risk; high iron, protein, vitamin D, calcium and manganese lower it.", True),
 ("Why TreeExplainer for CatBoost but KernelExplainer for the others?",
  "TreeExplainer computes exact values using the tree structure and is fast. TabPFN and TabFM have no trees, so a model-agnostic method was needed. The planned PermutationExplainer failed with a numba error on both Colab and Kaggle, so I used KernelExplainer.", True),
 ("Only 20-30 records for the foundation-model SHAP. Is that enough?",
  "It is enough to see which features lead and their direction, which agree with CatBoost's full-data SHAP and with the data correlations. It is not enough to trust the exact order, so I do not interpret rank differences. Larger samples are future work.", True),
 ("Can SHAP show causes?",
  "No. SHAP explains what the model uses, not causal effects. A model that learned a spurious pattern will give an explanation of that pattern.", True),
 ("What do beeswarm and waterfall plots show?",
  "Beeswarm: every record's contribution per feature, coloured by feature value, showing direction. Waterfall: for one patient, how each feature pushes the prediction from the baseline to the final value.", False),
 ("How would a doctor use your explanations?",
  "For one patient the waterfall plot lists which factors raised the risk (for example high stress, low iron) and which lowered it, so the doctor can check it against clinical judgement and give targeted advice.", False),
 ("Why did you compare SHAP with correlations?",
  "As an independent check that does not depend on the models: the seven top SHAP features are exactly the seven most correlated with risk, and the two features with zero correlation have zero importance.", False),
 ]),

("Computation and implementation",
 "",
 [
 ("What hardware and software did you use?",
  "Python on Kaggle and Google Colab with an NVIDIA T4 GPU; catboost, tabpfn, tabfm 1.0.0 (PyTorch backend), shap, scikit-learn, statsmodels, pandas, NumPy, matplotlib and seaborn.", True),
 ("What problems did you face?",
  "TabFM's runtime grew steeply and the full run did not finish; PermutationExplainer failed with a numba error, so I used KernelExplainer; TabFM crashed on single-row input, so I padded to two rows; TabPFN's checkpoint failed to load with new PyTorch, so I patched torch.load.", True),
 ("Does padding a single row change TabFM's prediction?",
  "No. I duplicate the row, predict both, and keep the first output. The prediction for that record is the same.", False),
 ("Which model is cheapest to deploy?",
  "CatBoost: once trained it predicts in milliseconds and needs no training data at prediction time. Foundation models need no training but pay at every prediction and must keep the training data as context.", True),
 ("Did you measure runtimes precisely?",
  "Approximately, as wall-clock time on shared cloud hardware. They show how cost grows with context, not exact benchmarks.", False),
 ]),

("Demo application (if asked to show it)",
 "The repository contains a working web app. Rehearse the demo once before the viva.",
 [
 ("Can you show a demonstration?",
  "Yes. The app has a React frontend and a FastAPI backend. On the Predict tab you enter a patient's values and get a risk tier from CatBoost, TabPFN and TabFM, each with a SHAP explanation; predictions are stored in MongoDB. The Analysis tab shows dataset statistics and the evaluation results.", True),
 ("How does each model run in the app?",
  "CatBoost runs locally with live SHAP. TabPFN uses Prior Labs' cloud API and needs a token (about 5-20 seconds per call). TabFM runs locally on CPU with a 500-row context and is slow (about 20-45 seconds per prediction on a laptop).", True),
 ("What happens if a model is not available?",
  "Each model fails independently; the panel shows 'not configured' with the reason, and CatBoost always works.", False),
 ("Is patient data safe in your app?",
  "It is a demonstration, not a clinical system. A real deployment would need authentication, encryption, consent and would avoid sending data to external APIs without approval.", False),
 ]),

("Limitations (tough questions)",
 "Never be defensive. Name the limitation, say why it happened, say how you reduced its impact, and say what you would do next.",
 [
 ("What are the main limitations of your study?",
  "Constructed dataset (not clinical validation); TabFM at 500 rows only; 2,000-row test subset and no significance tests at reduced sizes; small SHAP samples for the foundation models; CatBoost early stopping on the test set; one split and one seed; no ordinal models.", True),
 ("Can your results be generalised?",
  "Only to this dataset and to structured data of a similar kind. The consistent behaviour of two independent foundation models suggests the pattern is not specific to one model, but I tested only one dataset.", True),
 ("Your results might just be luck of one split. How do you know?",
  "The test set is large (4,322), so the accuracy intervals are narrow (+/-1.2 points). But variation between splits and seeds was not measured; repeated cross-validation is future work.", True),
 ("Some of your appendix code was reconstructed. Is your work reproducible?",
  "The main results come from the saved outputs of the notebook runs, and the code in the appendix follows the same procedure. Two parts cannot be reproduced exactly: the SHAP test samples had no fixed seed, and TabFM 1.0.0 may change. I state both in Section 3.10.", False),
 ("Why should we trust results from a model released only months ago?",
  "I did not trust it blindly: I tested it myself, documented its defects and workarounds, and compared it with an established model (TabPFN) and a tuned baseline.", False),
 ]),

("Conclusion and future work",
 "",
 [
 ("What is your final conclusion?",
  "On this dataset, zero-shot foundation models matched a tuned CatBoost without tuning, were much better with little data, and all three could be explained with SHAP; TabFM was slow at large context. It is a benchmark, not a clinical tool.", True),
 ("What future work do you recommend?",
  "Validate on real, ethically cleared clinical data (ideally from Nepal); full-context TabFM; repeat the scaling experiment on the full test set with several seeds and McNemar tests; repeated cross-validation; larger SHAP samples; ordinal models for the Moderate tier; ensembles and distillation for deployment.", True),
 ("What practical recommendation would you give?",
  "With a few hundred labelled records, start with a tabular foundation model such as TabPFN. With a large dataset and a need for fast predictions, a tuned CatBoost is as accurate and much cheaper. Always explain predictions and check them against the data.", True),
 ("If a Nepali hospital gave you 1,000 real records tomorrow, what would you do?",
  "Get ethical approval and anonymise the data, check quality, then run the same pipeline: stratified split, tuned CatBoost versus TabPFN/TabFM, macro metrics, McNemar, SHAP. With 1,000 records I would expect the foundation models to have an advantage, based on my scaling results.", False),
 ]),

("General machine learning fundamentals",
 "Examiners sometimes test basics. Short, correct answers are enough.",
 [
 ("What is overfitting and how did you prevent it?",
  "Fitting noise in the training data so the model performs worse on new data. I used cross-validation for tuning, early stopping, L2 regularisation, shallow symmetric trees, and a held-out test set.", True),
 ("What is the bias-variance trade-off?",
  "Simple models underfit (high bias); complex models overfit (high variance). Tuning depth and learning rate balances the two.", False),
 ("What is cross-validation? Why stratified?",
  "Splitting the training data into k folds, training on k-1 and validating on the remaining one, k times. Stratified folds keep the class proportions in every fold, which matters for imbalanced classes.", True),
 ("What is data leakage?",
  "When information from the test data influences training, giving over-optimistic results. Examples: fitting a scaler on all data, or tuning on the test set. I avoided fitted preprocessing; my one leak is early stopping on the test set, which I report.", True),
 ("Difference between bagging and boosting?",
  "Bagging (Random Forest) trains many trees independently on random samples and averages them to reduce variance. Boosting trains trees one after another, each correcting the previous errors, to reduce bias.", False),
 ("What is a confusion matrix?",
  "A table counting, for each true class, how many records were predicted as each class. The diagonal shows correct predictions.", False),
 ("Classification versus regression? Why is yours classification?",
  "Classification predicts categories; regression predicts numbers. My target is three risk tiers, so it is classification (with an ordinal nature).", False),
 ("What is a transformer?",
  "A neural network built on self-attention, which lets every element of the input attend to every other. It is the basis of large language models and of TabPFN and TabFM.", False),
 ("What is ordinal classification?",
  "Classification where classes have an order (Low < Moderate < High). Methods like Frank and Hall's split it into k-1 binary questions such as 'is risk above Low?'.", False),
 ]),

("Thesis format and process",
 "Short practical questions that sometimes come up.",
 [
 ("Which referencing style did you use?",
  "IEEE, numbered in order of first appearance, as required by the guidelines.", False),
 ("How did you ensure originality? What is your plagiarism percentage?",
  "The text is written in my own words and all sources are cited. The guideline requires below 20%. [Give your actual similarity report percentage.]", True),
 ("How long is the thesis?",
  "The main body (Chapters 1-5) is about 15,000 words, within the 15,000-30,000 word guideline, with 32 references, 23 tables and 19 figures.", False),
 ("How often did you meet your supervisor?",
  "[Give the actual number; the guideline requires at least four meetings, recorded in the progress form.]", False),
 ]),
]

TIPS = [
    ("Listen, pause, then answer", "Take two seconds to think. Repeat the question in your own words if it is long."),
    ("Answer short first, then add", "Give the one-sentence answer, then one reason, then stop. Let them ask more."),
    ("Use your numbers", "Quote exact figures: 78.51 / 78.57 / 77.88%, p > 0.05, 100-row result 61 vs 72 vs 74%."),
    ("Own the limitations", "Say 'That is a limitation, I report it in Section 5.2, and this is how I would fix it.'"),
    ("Never claim more than the data show", "Say 'no significant difference was detected', not 'the models are equal'. Say 'benchmark', not 'diagnostic tool'."),
    ("If you do not know", "Say 'I did not test that, but I would expect ... because ...' or 'I would need to check.' Never invent."),
    ("Point to the thesis", "'This is in Table 4.1 / Section 4.3.' It shows command of your work."),
    ("Link to Nepal and to users", "When relevant, mention low-cost lab tests, limited specialists outside cities and small local datasets."),
]
